name: deteksi_jerawat
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  camera: 0.11.0+2 
  http: ^0.13.4
  shared_preferences: ^2.0.15 
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  mime: ^2.0.0
  http_parser: ^4.0.2
  shimmer: ^3.0.0
  intl: ^0.19.0
  permission_handler: ^10.2.0
  connectivity_plus: ^6.1.0
  dio: ^5.3.2
  carousel_slider: ^5.0.0
  google_fonts: ^4.0.3
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.1
  flutter_datetime_picker_plus: ^2.1.0
  glassmorphism: ^3.0.0 
  animate_do: ^3.1.2
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geolocator: any
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"  # Untuk Android (opsional)
  # adaptive_icon_foreground: "assets/icon/foreground.png"  # Untuk Android (opsional)

flutter_native_splash:
  color: "#FFFFFF"  # Warna background
  image: assets/icon.png  # Path gambar splash
  android: true
  ios: true
  android_gravity: center  # Posisi gambar di Android
  ios_content_mode: center  # Posisi gambar di iOS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/profile/
    - assets/produk/
    - assets/login/
    - assets/fonts/
    - assets/skinpedia/
  
  fonts:
  - family: IsidoraSansAlt
    fonts:
      - asset: assets/fonts/IsidoraSansAlt-Bold.ttf
        weight: 700